### ISSUE TITLE
🚠 Create sub-tasks for API endpoints

### ISSUE THREAD

**Issue by josegoval** [josegoval/GuarderiaLaRanita#12]
Expected time: 1,5 hours.

- [x] Create endpoint sub-tasks on each major task
- [x] Define middlewares for each endpoint
- [x] Define request json objects types and response json objects types
- [x] Define complete process on each use case
